### ISSUE TITLE
Add new Drivers

### ISSUE THREAD

**Issue by rbonghi** [rbonghi/jetson_easy#10]
Following the @Rafcin issue #8 I open this new Issue to reply directly about it:

> If I flash the Jetpack 4.1.1 it won't overwrite my system right files right?
> 
> Also run this to fix the Mbs rate. By default its slow so even if you add a Ethernet cable it will be terribly slow.
> `echo "options iwlwifi 11n_disable=8" | sudo tee -a /etc/modprobe.d/iwlwifi.conf`
> 
> Also sorry I might be mistaken, but if you have the ability to modify the kernel, can you enable V4L2 drivers.
> `Device Drivers -> Multimedia Support -> Media USB Adapters -> USB Video Class V4L2`
> Sorry if its confusing, its 5am 💯

**Comment by rbonghi** [comment]
In these days I'm understanding how I can recompile the kernel for the nvidia Jetson AGX Xavier.

I see on this page https://developer.nvidia.com/embedded/linux-tegra the kernel for L4T 31.1, but I'm checking the hint from @griz1112 https://devtalk.nvidia.com/default/topic/1039294/jetson-agx-xavier/custom-kernel-selection-on-xavier-solved-/2

Do you have tried to recompile the kernel to add this new driver? Do you have seen  particular issues?

**Comment by Rafcin** [comment]
Yes i've compiled all the drivers but on my computer and then to the Xavier
flashing it. But yes i've compiled 99% of the drivers
Rafael Szuminski - Presentation

**Comment by Rafcin** [comment]
https://github.com/jtagxhub/jetpack-agx-build

**Comment by rbonghi** [comment]
Hi @Rafcin,

Where did you find this script to improve the performance of the Wi-Fi and Ethernet connection?
```console
echo "options iwlwifi 11n_disable=8" | sudo tee -a /etc/modprobe.d/iwlwifi.conf
```
I'm searching online, but I didn't find any relevant post about it

**Comment by Rafcin** [comment]
https://askubuntu.com/questions/824052/wifi-working-slower-than-it-should/824061#824061
Rafael Szuminski - Presentation

**Comment by Rafcin** [comment]
Let me see if I can get you some more useful stuff that can help fix the Jetson tonight, I've made plenty of modifications that you should probably have.

**Comment by rbonghi** [comment]
Hi @Rafcin ,

I'm checking the kernel configuration for: `USB Video Class V4L2`
> `Device Drivers -> Multimedia Support -> Media USB Adapters -> USB Video Class V4L2`

And from the configuration file in **/proc/config.gz** i can see (with the firmware L4T=31.1.0) is by default enabled. Below an extract of the document:
```
CONFIG_VIDEO_V4L2_SUBDEV_API=y
CONFIG_VIDEO_V4L2=y

# ....
# ....

#
# Supported MMC/SDIO adapters
#
# CONFIG_CYPRESS_FIRMWARE is not set
CONFIG_VIDEO_V4L2_TPG=m
```

**Comment by Rafcin** [comment]
When I originally flashed the device with the first 4.1 Jetpack it was not,
I'm still on the old version of Jetpack, I don't know how to update without
and any problems.

**Comment by rbonghi** [comment]
Keep me posted. Anyway I added in list this `CONFIG_VIDEO_V4L2` in list.

Now you can check directly when ./biddibi_boddibi_boo.sh start ;-)

**Comment by Rafcin** [comment]
Hooray!
