### ISSUE TITLE
errors :(

### ISSUE THREAD

**Issue by 14nrv** [rbonghi/jetson_easy#14]
Hi,
Nice project

I run the script on my VM (ubuntu) and I got those errors. Do u have an idea why?
I would like to have the ACM module

- I can manually make ssh on my jetson nano.
- I installed rsync on my vm.
- Linux r-nano 4.9.140-tegra #1 SMP PREEMPT Wed Mar 13 00:32:22 PDT 2019 aarch64 aarch64 aarch64 GNU/Linux

![Capture d’écran 2019-06-05 à 22 47 50](https://user-images.githubusercontent.com/34603467/58990242-c0000c80-87e5-11e9-91aa-5044b1062d1c.png)

**Comment by rbonghi** [comment]
Hi @14nrv ,

I will fix soon. The error start from my last updated of https://github.com/rbonghi/jetson_stats and doesn't find now all environment variables.

**Comment by rbonghi** [comment]
Thank you @14nrv ,

I will fix the installer for jetson-stats and I think jetson easy will start to work without any problem!

**Comment by 14nrv** [comment]
@rbonghi 

For my jetson nano (Kernel: 4.9.140, Jetpack 4.2 [L4T 32.1.0]), I made some others changes:
* modules/4-kernel_update/4-kernel_update.sh
```
# ...
case $JETSON_L4T in
  "32.1.0")
    KERNEL_LINK="https://developer.nvidia.com/embedded/dlc/l4t-sources-32-1-jetson-nano"
    KERNEL_INTERNAL_FOLDER="public_sources/kernel_src.tbz2"
    KERNEL_FOLDER="kernel/kernel-4.9"
    ;;
# ...
```

* modules/4-kernel_update/kernel_installer.sh
i replaced:
`sudo zcat $KERNEL_SRC_CONFIG > $KERNEL_CONFIG_FILE`
by:
`sudo sh -c 'zcat /proc/config.gz > .config'`
