### ISSUE TITLE
Default carrier board only?

### ISSUE THREAD

**Issue by jinchenglee** [rbonghi/jetson_easy#6]
I have a J120 carrier board, will the process work for non-default carrier board of Jetson TX1/2? Thanks.

**Comment by rbonghi** [comment]
Theoretically can works with all boards, but I didn't test if works.
Which error do you have?

Best

**Comment by jinchenglee** [comment]
Sorry for the late reply. Just found time to play with Auvidea J120 board with Jetson TX1. The repo jetson_easy works great. Thanks for the great work!

Only caveat is that I shall provide "-p <sudo passwd>" to the script, otherwise kernel build will hang.

**Comment by rbonghi** [comment]
Hi @jinchenglee,

 where you provide this "-p"? just to understand how I can improve my code :-)

**Comment by jinchenglee** [comment]
$ ./biddibi_boddibi_boo.sh -p <passwd>


Raffaello Bonghi <notifications@github.com> 于2018年7月20日周五 下午7:31写道：

**Comment by jinchenglee** [comment]
$ ./biddibi_boddibi_boo.sh -p <passwd>

**Comment by rbonghi** [comment]
I improved more part to setup the jetson_easy configuration.

Now you can store all configuration in a file
