### ISSUE TITLE
Support for Xavier

### ISSUE THREAD

**Issue by Spawn32** [rbonghi/jetson_easy#8]
Hi @rbonghi ,
Very nice and useful utility, thanks :)
Any chance to get an update so it also covers the Xavier ?

**Comment by AngelCrusher** [comment]
Mabey you should buy Raffaello one? Then he can cover it.

**Comment by rbonghi** [comment]
Hi @Spawn32,

I appreciate you use my system.
At this time I don't have any type of Jetson Xavier and I can't check if this system can work there.

However I'm checking jetson_easy with the new Jetpack 3.4

**Comment by rbonghi** [comment]
If you can help me! I am really great full for that!

At this time I don’t have a Xavier, but I can help you in your test to understand how my jestson easy is written.

**Comment by Rafcin** [comment]
I can run any code if you need to test it on the xavier, I have a bit of an
understanding of your tool, I've modified it a few times for the Tx2 to set
it up differently but I could take some time and understand it fully

**Comment by rbonghi** [comment]
Under testing: https://github.com/rbonghi/jetson_easy/tree/develop

When will be ready I'll merge on master ;-)

**Comment by rbonghi** [comment]
![screenshot from 2018-11-10 12-38-58](https://user-images.githubusercontent.com/4551246/48301728-b41fc680-e4f2-11e8-8607-56ae63102b39.png)

Now jetson_easy works with the NVIDIA Jetson AGX Xavier and with jetpacks: 4.0, 4.1, 4.1.1

**Comment by Rafcin** [comment]
If I flash the Jetpack 4.1.1 it won't overwrite my system right files right?

Also run this to fix the Mbs rate. By default its slow so even if you add a Ethernet cable it will be terribly slow.
`echo "options iwlwifi 11n_disable=8" | sudo tee -a /etc/modprobe.d/iwlwifi.conf`

Also sorry I might be mistaken, but if you have the ability to modify the kernel, can you enable V4L2 drivers. 
`Device Drivers -> Multimedia Support -> Media USB Adapters -> USB Video Class V4L2`
Sorry if its confusing, its 5am 💯

**Comment by rbonghi** [comment]
Hi @rbonghi,

I'm replying in a new issue. ;-)
